name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create'
        required: true
        default: 'v0.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20

      - name: Check out code
        uses: actions/checkout@v3

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Coverage
        run: make coverage

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
